name: Collect SS14 server data

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests

      - name: Fetch and append data
        run: python fetch_ss14_data.py

      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add data/history.csv
          git commit -m "Update data [skip ci]" || echo "No changes to commit"
          git push
